language: node_js
node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build

addons:
  sonarcloud:
    organization: "magoo-magoo-github"

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master